[window]
decorations = "None"
opacity = 0.95
blur = true
level = "AlwaysOnTop"
padding = {x = 10,y = 10}
dynamic_padding = true

[font]
size = 12.0 # Adjust the size as needed

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[env]
TERM = "xterm-256color"
